imus_test:
  imus:
    - name: "px_248"
      topic_imu_yaw: "/px_2_4_8/yaw"
      topic_imu_temperature: "/px_2_4_8/mavros/imu/temperature_imu"
      is_the_temperature_message_float_64: False
    - name: "px_cube"
      topic_imu_yaw: "/px_cube/yaw"
      topic_imu_temperature: "/px_cube/mavros/imu/temperature_imu"
      is_the_temperature_message_float_64: False
   