quaternion_to_euler_imus:
-
 name: px_2_4_8
 topic : /px_2_4_8/mavros/imu/data
 publish : /px_2_4_8/yaw
-
 name: myahrs
 topic : /myahrs/imu/data/not_filter
 publish : /myahrs/yaw
-
 name: px_cube
 topic : /px_cube/mavros/imu/data
 publish : /px_cube/yaw
-
 name: vectornav
 topic : /vectornav/imu/data
 publish : /vectornav/yaw
-
 name: px_2_4_8_filter
 topic : /px_2_4_8/imu/data/filter
 publish : /px_2_4_8/yaw_filter
-
 name: myahrs_filter
 topic : /myahrs/imu/data/filter
 publish : /myahrs/yaw_filter
-
 name: px_cube_filter
 topic : /px_cube/imu/data/filter
 publish : /px_cube/yaw_filter
-
 name: phidgets_filter
 topic : /phidgets/imu/data/filter
 publish : /phidgets/yaw_filter
-
 name: phidgets_other_filter
 topic : /phidgets/imu/data/other_filter
 publish : /phidgets/other_yaw_filter
-
 name: vectornav_filter
 topic : /vectornav/imu/data/filter
 publish : /vectornav/yaw_filter